### ISSUE TITLE
Improvements Tracker

### ISSUE THREAD

**Issue by Ghamza-Jd** [Ghamza-Jd/jarust#113]
- [x] Abstract the usage of the transport (#115)
- [x] Favour struct params over usual params, so the APIs have a named arguments
- [ ] Use `std::sync::Mutex` over `tokio::sync::Mutex` when possible (when we don't hold the mutex between await points)
- [x] Improve documentation
